version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-change-in-production
      - DATABASE_URL=sqlite:///instance/site.db
      - MAIL_SERVER=sandbox.smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USE_TLS=True
      - MAIL_USERNAME=your-mail-username
      - MAIL_PASSWORD=your-mail-password
      - MAIL_DEFAULT_SENDER=noreply@webapp.com
      - APPLICATION_NAME=Web App
      - FRONTEND_URL=http://localhost:5000
    volumes:
      - ./instance:/app/instance
      - ./app/static/uploads:/app/app/static/uploads
      - ./migrations:/app/migrations
    networks:
      - webapp-network
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - webapp-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./app/static:/var/www/static:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   networks:
  #     - webapp-network
  #   depends_on:
  #     - web
  #   restart: unless-stopped

volumes:
  redis_data:

networks:
  webapp-network:
    driver: bridge
